local colourUtils = {}

function colourUtils.hexToRgb(hex)
    hex = hex:gsub("#", "")  -- Remove the hash character if present

    local r = tonumber(hex:sub(1, 2), 16) / 255
    local g = tonumber(hex:sub(3, 4), 16) / 255
    local b = tonumber(hex:sub(5, 6), 16) / 255

    return {r, g, b}
end

function colourUtils.isHexColor(str)
    if type(str) == "string" then
        return string.match(str, "^#?%x%x%x%x%x%x$")
    else
        return false
    end
end


return colourUtils
